resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: nkcraddock/concourse-artifactory-resource
    tag: latest
 
resources:
- name: asm-core
  type: git
  source:
    uri: https://github.com/chamap1/asm-core.git
    branch: master
    username: chamap1
    password: Chandu!99!
    
- name: asmui_artifactory_repo
  type: artifactory
  source:
    url: http://artifactory.mpe.lab.vce.com:8080/artifactory
    path: concourse-demo/asmui
    regexp: (.*).war
    user: admin
    password: Vcem0123
 
jobs:
- name: package
  public: true
  plan:
  
  - get: asm-core
    trigger: true
  
  - task: compile
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: gradle}
 
      inputs:
      - name: asm-core
 
      outputs:
      - name: artifacts
      
      run:
        user: root
        path: bash
        dir: /asm-core
        args:
        - -exc
        - |
          echo "STARTING asm-core BUILD ...................... "          
          ./gradlew -x test --info
          find / -type d -name "artifacts"
          cp `find . -name "*.war"` ../artifacts
          echo "################################## FINISHED asm-core BUILD ...................... "
  
  - put: asmui_artifactory_repo
    params:
        file: ./artifacts/asmui.war
        
- name: deploy
  public: true
  plan:
  
  - get: asmui_artifactory_repo
    trigger: true
    passed:
      - package
  
  - task: copy
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alexedev/ubuntu-sshpass}
 
      inputs:
      - name: asmui_artifactory_repo
      
      run:
        user: root
        path: bash
        dir: /asmui_artifactory_repo
        args:
        - -exc
        - |
          sshpass -p "V1rtu@1c3!" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r asmui.war root@10.239.134.80:/root/asmui.war
